### ISSUE TITLE
Queue messenger configuration overrides template messenger configuration

### ISSUE THREAD

**Issue by berghaus** [PanDAWMS/panda-harvester#251] opened 2019-02-15 15:21 UTC
My queues operate with a configuration configuration like this [panda_queueconf.json](https://gist.github.com/berghaus/5d2ecf20fa2090919eb30fc07e6d4899). I added a queue to test pilot2. First I need a different submitter and messenger since the executable changes and r job specifications for pilot2 need to be in json:

```json
"CERN-EXTENSION_HARVESTER_2": {
    "queueStatus": "offline",
    "templateQueueName": "PRODUCTION_PUSH_TEMPLATE",
    "submitter": {
      "name": "HTCondorSubmitter",
      "module": "pandaharvester.harvestersubmitter.htcondor_submitter",
      "useAtlasGridCE": false,
      "x509UserProxy": "/data/atlpan/proxy/prod",
      "logDir": "/data/atlpan/condor_logs",
      "logBaseURL": "...",
      "nProcesses": 4,
      "templateFile": "/cephfs/atlpan/harvester/harvester_common/CERN_central_1/cern-extension_harvester_2.sdf",
      "executableFile": "/cephfs/atlpan/harvester/harvester_common/CERN_central_1/runpilot2-wrapper.sh",
      "ceHostname": "...",
      "ceEndpoint": "..."
    },
    "messenger": {
      "name": "SharedFileMessenger",
      "module": "pandaharvester.harvestermessenger.shared_file_messenger",
      "jobSpecFileFormat": "json",
      "accessPoint": "/cephfs/atlpan/harvester/harvester_wdirs/${harvesterID}/${_workerID_3.2}/${_workerID_1.0}/${workerID}"
    }
```

As expected the job specification for `CERN-EXTENSION_HARVESTER_2` are in json format. However many (but not all) of the job specification for `CERN-EXTENSION_HARVESTER` are also in json when I expected them all to be cgi.

**Comment by berghaus** [comment] 2019-02-15 15:24
As a correction, with the queue offline of course I see no jobs for `CERN-EXTENSION_HARVESTER_2`, but still many of the job specifications for `CERN-EXTENSION_HARVESTER` are in json.

**Comment by mightqxc** [comment] 2019-02-19 15:35
I cannot reproduce the issue.
Please provides an example worker and its workspec dump and related configID if this happens again.

**Comment by mightqxc** [comment] 2019-02-20 09:45
I cannot reproduce this issue easily. But I found potential problem in code, which should be fixed in:
https://github.com/PanDAWMS/panda-harvester/pull/252

**Comment by berghaus** [comment] 2019-02-22 09:33
OK let me update the CERN_central_1 harvesters and try whether this fixes the problem.

**Comment by mightqxc** [comment] 2019-03-25 13:24
I think the issue has been fixed.
Closing now.

**Closed by mightqxc** 2019-03-25 13:24 UTC
